### PR TITLE
Settings button created

### PR DESCRIPTION
**Pull request by josephbondoc**
Wondering how to go about creating a custom button which would use a clickable image which will trigger an alert.

Do I use TouchableOpacity? Is there another method? Please halp lol
:)

### CODE REVIEW

**Comment by sshenis** [comment]
Jay, are you trying to use pop or alert??

**Comment by sshenis** [comment]
Jay, for now remove everything in your settings and button (settingsStyles.js)

- ok so how i went about it is that everytime you click on the gear, the opacity of the text will go from 0 to 1 (100%)
 
so to make that happen, make a variable for opacity and set it 0
then make an if else statement saying
if showGear is true then the opacity variable will be set to 1 (which is 100%) if not, then it will be back to 0


then in ur return, create a separate view and in line style that with opacity then set the value for that as the variable u used for opacity
then add a dummy text in and style that big so you can see it 

then in ur <Image /> inline style everything
bottom:0, width: 50, height: 50

**Comment by josephbondoc** [comment]
When you say separate view, do you mean a separate view apart from my main one (which currently contains my image)

Or are you talking about that view in particular?

**Comment by sshenis** [comment]
Y

> When you say **CREATE** separate view, do you mean a separate view apart from my main one (which currently contains my image)
> 
> Or are you talking about that view in particular?

it will be a SEPARATE VIEW. So a VIEW within a view.

**Pull request merged**
